### ISSUE TITLE
traceback on run.py

### ISSUE THREAD

**Issue by robclemamzn** [shacharmo/KlvOverMpegTSExtractor#4]
getting a runtime error on basic first run. it seems something isnt declared. 
using python v3.12 if it matters.

Traceback (most recent call last):
  File "/private/tmp/Klv_extractor/run.py", line 40, in <module>
    extract_klv(args.file)
  File "/private/tmp/Klv_extractor/run.py", line 10, in extract_klv
    packet.structure()
    ^^^^^^^^^^^^^^^^
AttributeError: 'UnknownElement' object has no attribute 'structure'
---------------------------------

**Comment by AlejandroL2** [comment]
I had the same error.  I solved change the version of ffmpeg. In the version 6.1.1 doesnt have problems.
